trainer:
   name: saket_local
   
server:
  port: 8900   
  
---
spring:
  profiles: dev

trainer:
  name: saket_local_Dev
  
---
spring:
  profiles: test

trainer:
  name: saket_local_test     
---
spring:
  profiles:
    active: test,dev  
  